// ============================================================
// ADMIN AUTHORIZATION MIDDLEWARE
// File: middlewares/adminMiddleware.js
// ============================================================
//
// Purpose:
// - Verify that the authenticated user has permanent admin
//   privileges.
// - Works with the JWT structure generated by authController.js.
// - Supports admin/customer mode switching without removing
//   the user's underlying admin authorization.
//
// IMPORTANT:
// authMiddleware.js must run BEFORE this middleware.
// Example:
// router.get("/all", verifyToken, isAdmin, getAllBookings);
// ============================================================

const isAdmin = (req, res, next) => {
    try {

        // ----------------------------------------------------
        // 1. Make sure authentication middleware ran first
        // ----------------------------------------------------
        if (!req.user) {
            return res.status(401).json({
                success: false,
                message: "Authentication required."
            });
        }

        // ----------------------------------------------------
        // 2. Check permanent admin authorization
        //
        // authController.js creates admin JWTs with:
        // isAdmin: true
        // roles: ["admin", "customer"]
        // ----------------------------------------------------
        const hasAdminFlag =
            req.user.isAdmin === true;

        const hasAdminRole =
            Array.isArray(req.user.roles) &&
            req.user.roles.includes("admin");

        // ----------------------------------------------------
        // 3. Allow access if either trusted admin indicator
        //    confirms admin privileges.
        // ----------------------------------------------------
        if (!hasAdminFlag && !hasAdminRole) {
            return res.status(403).json({
                success: false,
                message: "Access denied. Admins only."
            });
        }

        // ----------------------------------------------------
        // 4. User is authorized
        // ----------------------------------------------------
        next();

    } catch (error) {

        console.error(
            "Admin authorization error:",
            error
        );

        return res.status(500).json({
            success: false,
            message: "Authorization check failed."
        });
    }
};


// ============================================================
// EXPORT
// ============================================================

module.exports = isAdmin;